apps/diary/urls.py
from django.urls import path

from . import views


app_name = 'diary'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('add/', views.PostCreateView.as_view(), name='add'),
    path('post/<int:pk>/', views.EntryDetailView.as_view(), name='entry'),
    path('archive/', views.ArchiveView.as_view(), name='archive'),
    path('edit/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
]

apps/users/urls.py
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('', include('apps.diary.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('apps.users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

apps/diary/models.py
from django.db import models
from django.shortcuts import reverse
from django.conf import settings


class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    pub_date = models.DateField(auto_now_add=True)
    content = models.TextField()

    objects = models.Manager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('diary:entry', args=[self.id])

apps/users/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):

    def __str__(self):
        return self.first_name + ' ' + self.last_name

apps/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = (
            'first_name', 'last_name',
            'email', 'username',
        )

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = (
            'first_name', 'last_name',
            'email', 'username',
        )

apps/diary/views.py
from django.shortcuts import redirect
from django.views.generic import  DetailView, ListView, TemplateView
from django.views.generic.edit import CreateView, UpdateView

from .models import Post


class HomePageView(TemplateView):
    template_name = 'diary/home.html'

    def get_context_data(self, **kwargs):
        if self.request.user.is_authenticated:
            kwargs['number'] = Post.objects.filter(
                author=self.request.user).count()
            kwargs['post_list'] = Post.objects.filter(
                author=self.request.user
            ).order_by('-id')[:5]
        return super(). get_context_data(**kwargs)


class PostCreateView(CreateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        new_post = form.save(commit=False)
        new_post.author = self.request.user
        new_post.save()
        return redirect(new_post.get_absolute_url())


class EntryDetailView(DetailView):
    model = Post

    def get_queryset(self):
        return super().get_queryset().filter(author=self.request.user)


class ArchiveView(ListView):
    
    def get_queryset(self):
        return Post.objects.filter(author=self.request.user).order_by('-id')


class PostUpdateView(UpdateView):
    model = Post
    fields = ['title', 'content']

apps/users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views.generic import DetailView

from .models import CustomUser
from .forms import CustomUserCreationForm


class SignUp(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/signup.html'


class ProfileView(DetailView):
    model = CustomUser

    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(username=
                                          self.request.user.username)

apps/diary/templates/base.html
{% load static %}

<!DOCTYPE html> 
<html>
    <head>
        <meta charset="utf-8">
        <title>Diary App!</title>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    </head>
    <body>
            <nav class="navbar navbar-expand-lg navbar-light bg-light pushdown">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                      <a class="navbar-brand" href="{% url 'diary:home' %}">Diary App!</a>
                      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'diary:home' %}">Home</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'diary:add' %}">Add Entry</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'diary:archive' %}">Archive</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:profile' user.id %}">My Profile</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="#">Add Entry</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Archive</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">My Profile</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link disabled" href="#">Disabled</a>
                        </li>
                        {% endif %}
                      </ul>             
                      <form class="form-inline ml-auto">
                            {% if user.is_authenticated %}
                            <a href="{% url 'logout' %}" class="btn btn-outline-secondary">Log out</a>
                            {% else %}
                            <a href="{% url 'login' %}" class="btn btn-primary">Log in</a>
                            {% endif %}
                        </form>

                    </div>
            </nav>
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>

apps/diary/templates/diary/add_entry.html
{% extends 'diary/base.html' %}

{% load crispy_forms_tags %}
{% block content %} 
    {% if user.is_authenticated %}
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="card card-signin my-5">
                    <div class="card-body">
                        <h5 class="card-title text-center">Add an Entry</h5>
                        <form class="form-signin" method="POST">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <input type="submit" value="Add Post!" class="btn btn-lg btn-primary btn-block text-uppercase"/>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-2"></div>
        </div>
    {% else %}

    {% endif %}

{% endblock content %}

apps/diary/templates/diary/archive.html
{% extends 'diary/base.html' %}

{% block content %}

    {% if user.is_authenticated %}
        <div class="row">
            <div class="card card-signin my-5">
                <div class="card-body">
                        <h5 class="card-title text-center">Archive of your diary entries.</h5>
                        {% for item in object_list %}
                            <article class="media content-section">
                                <div class="media-body">
                                <div class="article-metadata">
                                    <small class="text-muted">{{ item.pub_date|date:"F d, Y" }}</small>
                                </div>
                                <h2><a class="article-title" href="{% url 'entry' item.id %}">{{ item.title }}</a></h2>
                                <p class="article-content">{{ item.content }}</p>
                                </div>
                            </article>
                        {% endfor %}
                </div>
            </div>
        </div>
        

    {% else %}
        You are not logged in.

    {% endif %}



{% endblock content %}

apps/diary/templates/diary/detail_entry.html
{% extends 'diary/base.html' %}

{% block content %}
    
    {% if user.is_authenticated %}
        {% if object %}
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <div class="card card-signin my-5">
                        <div class="card-body">
                            <h3 class="card-title text-center">{{object.title}}</h5>
                            
                            <h5>written on: {{ object.pub_date }} </h5>
                            <p>{{ object.content }}</p>
                            <br><br>
                            
                        </div>
                    </div>
                </div>
                <div class="col-md-4"></div>
            </div>
        {% else %}
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <div class="card card-signin my-5">
                        <div class="card-body">
                            <h2 class="font-weight-bold">Hold it right there!</h2>
                            <h4 class="text-danger">This is someone else's diary entry.</h4>
                        </div>
                    </div>
                </div>
                <div class="col-md-3"></div>
            </div>
        {% endif %}

    {% else %}
        Oops! You are not logged in.

    {% endif %}

{% endblock content %}


<div class="row">
        <div class="card card-signin my-5">
            <div class="card-body">
                    <h5 class="card-title text-center">Archive of your diary entries.</h5>
                    {% for item in object_list %}
                        <article class="media content-section">
                            <div class="media-body">
                            <div class="article-metadata">
                                <small class="text-muted">{{ item.pub_date|date:"F d, Y" }}</small>
                            </div>
                            <h2><a class="article-title" href="{% url 'entry' item.id %}">{{ item.title }}</a></h2>
                            <p class="article-content">{{ item.content }}</p>
                            </div>
                        </article>
                    {% endfor %}
            </div>
        </div>
    </div>

apps/diary/templates/diary/home.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="row">
            <div class="col-md-4">
                <div class="card-welcome">
                        <h3>Hi, {{ user.first_name }}.</h3><br><br>
                        <h4>You have made <em>{{number}}</em> diary entries.</h4><br><br>
                        <h4>memory: {{ user.memory }}</h4>
                </div>    
            </div>
            <div class="col-md-1"></div>
            <div class="col-md-7 card-timeline">
                <h2>Your Timeline.</h2>
                <ul>
                    {% for item in post_list %}
                        
                        <article class="media content-section">
                                <div class="media-body">
                                <div class="article-metadata">
                                    <small class="text-muted">{{ item.pub_date|date:"F d, Y" }}</small>
                                </div>
                                <h2><a class="article-title" href="{{ item.get_absolute_url }}">{{ item.title }}</a></h2>
                                <p class="article-content">{{ item.content }}</p>
                                </div>
                        </article>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% else %}
        <div class="jumbotron unauth-jumb">
            <h1 class="display-4">Welcome!</h1>
            <p class="lead">This is a simple diary app that lets you add diary entries in order for you to improve your memory.</p>
            <hr class="my-4">
            <p>Start now!</p>
            <p class="lead">
              <a class="btn btn-primary btn-lg" href="{% url 'login' %}" role="button">Login</a>
              <a class="btn btn-primary btn-lg" href="{% url 'users:signup' %}" role="button">Signup</a>
            </p>
          </div>
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'users:signup' %}">Signup</a>
    {% endif %}
{% endblock content %}

apps/diary/templates/diary/post_detail.html
{% extends 'base.html' %}

{% block content %}
    
    {% if user.is_authenticated %}
        {% if object %}
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <div class="card card-signin my-5">
                        <div class="card-body">
                            <h3 class="card-title text-center">{{object.title}}</h3>
                            <h4> by: {{ object.author }} </h4>
                            <h5>written on: {{ object.pub_date }} </h5>
                            <p>{{ object.content }}</p>
                            <br><br><br>
                            <form action="{% url 'diary:update' object.id %}" method="get">
                                <button type="submit" class="btn btn-lg btn-primary btn-block ">edit this...</button>
                            </form>

                            <br><br>
                        </div>
                    </div>
                </div>
                <div class="col-md-4"></div>
            </div>
        {% else %}
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <div class="card card-signin my-5">
                        <div class="card-body">
                            <h2 class="font-weight-bold">Hold it right there!</h2>
                            <h4 class="text-danger">This is someone else's diary entry.</h4>
                        </div>
                    </div>
                </div>
                <div class="col-md-3"></div>
            </div>
        {% endif %}
    {% else %}
        Oops! You are not logged in.
    {% endif %}
{% endblock content %}

apps/diary/templates/diary/post_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block content %} 
    {% if user.is_authenticated %}
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="card card-signin my-5">
                    <div class="card-body">
                        <h5 class="card-title text-center">Add an Entry</h5>
                        <form class="form-signin" method="POST">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <input type="submit" value="Add Post!" class="btn btn-lg btn-primary btn-block text-uppercase"/>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-2"></div>
        </div>
   {% endif %}

{% endblock content %}

apps/diary/templates/diary/post_list.html
{% extends 'base.html' %}

{% block content %}

    {% if user.is_authenticated %}
        <div class="row">
            <div class="card card-signin my-5">
                <div class="card-body">
                        <h5 class="card-title text-center">Archive of your diary entries.</h5>
                        {% for item in object_list %}
                            <article class="media content-section">
                                <div class="media-body">
                                <div class="article-metadata">
                                    <small class="text-muted">{{ item.pub_date|date:"F d, Y" }}</small>
                                </div>
                                <h2><a class="article-title" href="{{ item.get_absolute_url }}">{{ item.title }}</a></h2>
                                <p class="article-content">{{ item.content }}</p>
                                </div>
                            </article>
                        {% endfor %}
                </div>
            </div>
        </div>
    {% else %}
        You are not logged in.
    {% endif %}
{% endblock content %}

apps/users/templates/users/base.html
{% load static %}

<!DOCTYPE html> 
<html>
    <head>
        <meta charset="utf-8">
        <title>Diary App!</title>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    </head>
    <body>
            <nav class="navbar navbar-expand-lg navbar-light bg-light pushdown">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                      <a class="navbar-brand" href="{% url 'home' %}">Diary App!</a>
                      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home' %}">Home</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'addentry' %}">Add Entry</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'archive' %}">Archive</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'profile' user.id %}">My Profile</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="#">Add Entry</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Archive</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">My Profile</a>
                        </li>
                        {% endif %}
                      </ul>
                    
                      <form class="form-inline ml-auto">
                            {% if user.is_authenticated %}
                            <a href="{% url 'logout' %}" class="btn btn-outline-secondary">Log out</a>
                            {% else %}
                            <a href="{% url 'login' %}" class="btn btn-primary">Log in</a>
                            {% endif %}
                        </form>

                    </div>
            </nav>
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>

apps/users/templates/users/customuser_detail.html
{% extends 'base.html' %}

{% block content %}

    {% if user.is_authenticated %}
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <div class="card card-signin my-5">
                    <div class="card-body">
                        <h3 class="card-title text-center">{{object.first_name}} {{ object.last_name }}</h3>
                    </div>
                </div>
            </div>
            <div class="col-md-4"></div>
        </div>
    {% else %}
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <div class="card card-signin my-5">
                    <div class="card-body">
                        <h2 class="font-weight-bold">Hold it right there!</h2>
                        <h4 class="text-danger">You are not allowed on this page.</h4>
                        <p class="text-muted">Please click the link below to log in.</p>
                        <br>
                        <a class="btn btn-primary btn-md text-center align-center" href="{% url 'login' %}" role="button">Login</a>        
                    </div>
                </div>
               </div>

            <div class="col-md-3"></div>
        </div>
    {% endif %}
{% endblock content %}

apps/users/templates/users/profile.html
{% extends 'users/base.html' %}

{% block content %}

    {% if user.is_authenticated %}
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <div class="card card-signin my-5">
                    <div class="card-body">
                        <h3 class="card-title text-center">{{object.first_name}} {{ object.last_name }}</h5>
                        
                        <h4> {{ object.gender}} </h4> &nbsp; <h4> {{ object.age }} </h4> <br>
                        <h4> Country: <em> {{ object.country }} </em></h4> <h5>Memory: <em> {{ object.memory }} </em></en></h5>
                        <br><br>
                        <p> {{ object.about }} </p>


                        
                    </div>
                </div>
            </div>
            <div class="col-md-4"></div>
        </div>
    {% else %}
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <div class="card card-signin my-5">
                    <div class="card-body">
                        <h2 class="font-weight-bold">Hold it right there!</h2>
                        <h4 class="text-danger">You are not allowed on this page.</h4>
                        <p class="text-muted">Please click the link below to log in.</p>
                        <br>
                        <a class="btn btn-primary btn-md text-center align-center" href="{% url 'login' %}" role="button">Login</a>        
                    </div>
                </div>
               </div>

            <div class="col-md-3"></div>
        </div>
    {% endif %}
{% endblock content %}

apps/users/templates/users/signup.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block title %}Sign Up {% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <h5 class="card-title text-center">Sign up</h5>
                    <form class="form-signin" method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input type="submit" value="Sign Up!" class="btn btn-lg btn-primary btn-block text-uppercase"/>
                    </form>

                </div>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock content %}